export const ADD_COUNTER = 'ADD_COUNTER'
export const TEST_BLOCK_MOVED = 'TEST_BLOCK_MOVED'
export const DRAG_TEST_BLOCK = 'DRAG_TEST_BLOCK'
export const CHAIN_SELECTED = 'CHAIN_SELECTED'
export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE'

export const FORM_TEMPLATE_FETCH_SUCCSEED = 'FORM_TEMPLATE_FETCH_SUCCSEED'
export const CHAIN_TEMPLATE_NAME_CHANGED = 'CHAIN_TEMPLATE_NAME_CHANGED'
export const FORM_TEMPLATE_FETCH_FAIL = 'FORM_TEMPLATE_FETCH_FAIL'
export const CHAIN_EDITOR_TEMPLATE_FETCH_SUCCEED = 'CHAIN_EDITOR_TEMPLATE_FETCH_SUCCEED'
export const CHAIN_EDITOR_TEMPLATE_FETCH_FAIL = 'CHAIN_EDITOR_TEMPLATE_FETCH_FAIL'
export const SCHEDULE_TIME_CHANGED = "SCHEDULE_TIME_CHANGED";
export const SCHEDULE_DATE_CHANGED = "SCHEDULE_DATE_CHANGED";
export const SCHEDULE_AMOUNT_OF_TIMES_CHANGED = "SCHEDULE_AMOUNT_OF_TIMES_CHANGED";


export const TEST_FETCH_SUCCEED = 'TEST_FETCH_SUCCEED'
export const TEST_FETCH_FAIL = 'TEST_FETCH_FAIL'

export const DATA_TEMPLATE_LIST_SUCCEED = 'DATA_TEMPLATE_LIST_SUCCEED'
export const DATA_TEMPLATE_LIST_FAIL = 'DATA_TEMPLATE_LIST_FAIL'
export const CHAIN_TEMPLATE_DELETED = 'CHAIN_TEMPLATE_DELETED'
export const CHAIN_TEMPLATE_ADDED = 'CHAIN_TEMPLATE_ADDED'
export const TEST_BLOCK_CLICKED = 'TEST_BLOCK_CLICKED'
export const CLOSE_BUTTON_CLICKED = 'CLOSE_BUTTON_CLICKED'
export const SUBMIT_BUTTON_CLICKED = 'SUBMIT_BUTTON_CLICKED'
export const SUBMIT_CHAIN_TEMPLATE_SUCCEED = 'SUBMIT_CHAIN_TEMPLATE_SUCCEED'
export const SUBMIT_CHAIN_TEMPLATE_FAIL = 'SUBMIT_CHAIN_TEMPLATE_FAIL'

