export const ADD_COUNTER = 'ADD_COUNTER';
export const TEST_BLOCK_MOVED = 'TEST_BLOCK_MOVED';
export const DRAG_TEST_BLOCK = 'DRAG_TEST_BLOCK';
export const CHAIN_SELECTED = 'CHAIN_SELECTED';
export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE';
export const TEMPLATE_FORM_INPUT_CHANGE = 'TEMPLATE_FORM_INPUT_CHANGE';
export const FORM_TEMPLATE_FETCH_SUCCSEED = 'FORM_TEMPLATE_FETCH_SUCCSEED';
export const CHAIN_TEMPLATE_NAME_CHANGED = 'CHAIN_TEMPLATE_NAME_CHANGED';
export const FORM_TEMPLATE_FETCH_FAIL = 'FORM_TEMPLATE_FETCH_FAIL';
export const CHAIN_EDITOR_TEMPLATE_FETCH_SUCCEED = 'CHAIN_EDITOR_TEMPLATE_FETCH_SUCCEED';
export const CHAIN_EDITOR_TEMPLATE_FETCH_FAIL = 'CHAIN_EDITOR_TEMPLATE_FETCH_FAIL';
export const SCHEDULE_TIME_CHANGED = "SCHEDULE_TIME_CHANGED";
export const SCHEDULE_DATE_CHANGED = "SCHEDULE_DATE_CHANGED";
export const SCHEDULE_AMOUNT_OF_TIMES_CHANGED = "SCHEDULE_AMOUNT_OF_TIMES_CHANGED";
export const SELECT_CHAIN = "SELECT_CHAIN";

export const TEST_FETCH_SUCCEED = 'TEST_FETCH_SUCCEED';
export const TEST_FETCH_FAIL = 'TEST_FETCH_FAIL';

export const DATA_TEMPLATE_LIST_SUCCEED = 'DATA_TEMPLATE_LIST_SUCCEED';
export const DATA_TEMPLATE_LIST_FAIL = 'DATA_TEMPLATE_LIST_FAIL';
export const CHAIN_TEMPLATE_DELETED = 'CHAIN_TEMPLATE_DELETED';
export const CHAIN_TEMPLATE_ADDED = 'CHAIN_TEMPLATE_ADDED';
export const TEST_BLOCK_CLICKED = 'TEST_BLOCK_CLICKED';
export const CLOSE_BUTTON_CLICKED = 'CLOSE_BUTTON_CLICKED';
export const SUBMIT_BUTTON_CLICKED = 'SUBMIT_BUTTON_CLICKED';
export const SUBMIT_CHAIN_TEMPLATE_SUCCEED = 'SUBMIT_CHAIN_TEMPLATE_SUCCEED';
export const SUBMIT_CHAIN_TEMPLATE_FAIL = 'SUBMIT_CHAIN_TEMPLATE_FAIL';

export const FORM_BUILDER_CHAINS_FETCH_SUCCEED = 'FORM_BUILDER_CHAINS_FETCH_SUCCEED';
export const FORM_BUILDER_CHAINS_FETCH_FAIL = 'FORM_BUILDER_CHAINS_FETCH_FAIL';

export const UPDATE_CHAIN_FORM_FAIL = 'UPDATE_CHAIN_FORM_FAIL';
export const UPDATE_CHAIN_FORM_SUCCEED = 'UPDATE_CHAIN_FORM_SUCCEED';

export const NEW_FIELD_ADDED = 'NEW_FIELD_ADDED';
export const ON_FIELDS_VALUES_UPDATE = 'ON_FIELDS_VALUES_UPDATE';
export const FIELD_WAS_REMOVED = 'FIELD_WAS_REMOVED';

export const TEST_BUILDER_TESTS_FETCH_SUCCEED = 'TEST_BUILDER_TESTS_FETCH_SUCCEED';
export const TEST_BUILDER_TESTS_FETCH_FAIL = 'TEST_BUILDER_TESTS_FETCH_FAIL';
export const TEST_SELECTED = 'TEST_SELECTED';
export const TEST_BUILDER_FORM_INPUT_CHANGED = 'TEST_BUILDER_FORM_INPUT_CHANGED';
export const ADD_NEW_TEST = 'ADD_NEW_TEST';
export const RESET_MODIFICATION_MARKERS = 'RESET_MODIFICATION_MARKERS';
