export const TEST_BLOCK_MOVED = 'TEST_BLOCK_MOVED';
export const CHAIN_SELECTED = 'CHAIN_SELECTED';
export const FORM_INPUT_CHANGE = 'FORM_INPUT_CHANGE';
export const TEMPLATE_FORM_INPUT_CHANGE = 'TEMPLATE_FORM_INPUT_CHANGE';
export const FORM_TEMPLATE_FETCH_SUCCSEED = 'FORM_TEMPLATE_FETCH_SUCCSEED';
export const CHAIN_TEMPLATE_NAME_CHANGED = 'CHAIN_TEMPLATE_NAME_CHANGED';
export const CHAIN_TEMPLATE_MARKER_CHANGED = 'CHAIN_TEMPLATE_MARKER_CHANGED';
export const FORM_TEMPLATE_FETCH_FAIL = 'FORM_TEMPLATE_FETCH_FAIL';
export const CHAIN_EDITOR_TEMPLATE_FETCH_SUCCEED = 'CHAIN_EDITOR_TEMPLATE_FETCH_SUCCEED';
export const SCHEDULE_TIME_CHANGED = "SCHEDULE_TIME_CHANGED";
export const SCHEDULE_DATE_CHANGED = "SCHEDULE_DATE_CHANGED";
export const SCHEDULE_AMOUNT_OF_TIMES_CHANGED = "SCHEDULE_AMOUNT_OF_TIMES_CHANGED";
export const DUPLICATE_CURRENT_CHAIN = 'DUPLICATE_CURRENT_CHAIN';
export const DATA_TEMPLATE_ADDED = 'DATA_TEMPLATE_ADDED';
export const GROUP_ADDED = 'GROUP_ADDED';

export const ORDERS_FETCH_SUCCEED = 'ORDERS_FETCH_SUCCEED';
export const ORDERS_FETCH_FAIL = 'ORDERS_FETCH_FAIL';

export const ORDERS_CSV_FETCH_SUCCEED = 'ORDERS_CSV_FETCH_SUCCEED';
export const ORDERS_CSV_FETCH_FAIL = 'ORDERS_CSV_FETCH_FAIL';

export const TEST_FETCH_SUCCEED = 'TEST_FETCH_SUCCEED';

export const FILTER_DATA_DIRECTORY = 'FILTER_DATA_DIRECTORY';

export const DATA_TEMPLATE_LIST_SUCCEED = 'DATA_TEMPLATE_LIST_SUCCEED';
export const DATA_TEMPLATE_LIST_FAIL = 'DATA_TEMPLATE_LIST_FAIL';
export const CHAIN_TEMPLATE_DELETED = 'CHAIN_TEMPLATE_DELETED';
export const CHAIN_TEMPLATE_ADDED = 'CHAIN_TEMPLATE_ADDED';
export const TEST_BLOCK_CLICKED = 'TEST_BLOCK_CLICKED';
export const CLOSE_BUTTON_CLICKED = 'CLOSE_BUTTON_CLICKED';
export const SUBMIT_CHAIN_TEMPLATE_SUCCEED = 'SUBMIT_CHAIN_TEMPLATE_SUCCEED';
export const SUBMIT_RERUN_ORDER_SUCCEED = 'SUBMIT_RERUN_ORDER_SUCCEED';

export const FORM_BUILDER_CHAINS_FETCH_SUCCEED = 'FORM_BUILDER_CHAINS_FETCH_SUCCEED';

export const UPDATE_CHAIN_FORM_SUCCEED = 'UPDATE_CHAIN_FORM_SUCCEED';

export const NEW_FIELD_ADDED = 'NEW_FIELD_ADDED';
export const ON_FIELDS_VALUES_UPDATE = 'ON_FIELDS_VALUES_UPDATE';
export const FIELD_WAS_REMOVED = 'FIELD_WAS_REMOVED';

export const TEST_BUILDER_TESTS_FETCH_SUCCEED = 'TEST_BUILDER_TESTS_FETCH_SUCCEED';
export const TEST_SELECTED = 'TEST_SELECTED';
export const TEST_BUILDER_FORM_INPUT_CHANGED = 'TEST_BUILDER_FORM_INPUT_CHANGED';
export const ADD_NEW_TEST = 'ADD_NEW_TEST';
export const RESET_MODIFICATION_MARKERS = 'RESET_MODIFICATION_MARKERS';
export const LOGIN_BUTTON_CLICKED = 'LOGIN_BUTTON_CLICKED';
export const LOGIN_PASSWORD_CHANGE= 'LOGIN_PASSWORD_CHANGE';

export const DATA_TEMPLATES_FETCH_SUCCESS = 'DATA_TEMPLATES_FETCH_SUCCESS';
export const DATA_TEMPLATE_SELECTED = 'DATA_TEMPLATE_SELECTED';
export const DATA_TEMPLATES_INPUT_CHANGE = 'DATA_TEMPLATES_INPUT_CHANGE';
export const DATA_TEMPLATE_NAME_CHANGED = 'DATA_TEMPLATE_NAME_CHANGED';
export const NEW_DATA_TEMPLATE_ADDED = 'NEW_DATA_TEMPLATE_ADDED';
export const NEW_DATA_TEMPLATE_PARAM_ADDED = 'NEW_DATA_TEMPLATE_PARAM_ADDED';
export const UPDATE_DATA_TEMPLATE_SUCCESS = 'UPDATE_DATA_TEMPLATE_SUCCESS';

export const ORDER_CREATED = 'ORDER_CREATED';
export const CLEAR_ID_ORDER_ALERT = 'CLEAR_ID_ORDER_ALERT';

export const LAUNCHER_STANDS_FETCH_SUCCEED = 'LAUNCHER_STANDS_FETCH_SUCCEED';
export const LAUNCHER_USER_GROUPS_FETCH_SUCCEED = 'LAUNCHER_USER_GROUPS_FETCH_SUCCEED';
export const GROUP_NAME_CHANGE = 'GROUP_NAME_CHANGE';
export const CREATE_GROUP_CLICKED = 'CREATE_GROUP_CLICKED';
export const DATA_GROUP_TEMPLATE_LIST_SUCCEED = 'DATA_GROUP_TEMPLATE_LIST_SUCCEED';
export const TEMPLATE_GROUP_FORM_INPUT_CHANGE = 'TEMPLATE_GROUP_FORM_INPUT_CHANGE';
export const GROUP_SELECTED = 'GROUP_SELECTED';
export const FORM_GROUPS_FETCH_SUCCEED = 'FORM_GROUPS_FETCH_SUCCEED';
export const FORM_GROUPS_FOR_MEMBERS_FETCH_SUCCEED = 'FORM_GROUPS_FOR_MEMBERS_FETCH_SUCCEED';

export const TEST_BUILDER_AS_FETCH_SUCCEED = 'TEST_BUILDER_AS_FETCH_SUCCEED';
export const TEST_BUILDER_STANDS_FETCH_SUCCEED = 'TEST_BUILDER_STANDS_FETCH_SUCCEED';
export const TEST_AS_SELECTED = 'TEST_AS_SELECTED';
export const DUPLICATE_CURRENT_TEST = 'DUPLICATE_CURRENT_TEST';
export const TEST_STANDS_INPUT_CHANGE = 'TEST_STANDS_INPUT_CHANGE';
export const CLEAR_TEST_FILTER = 'CLEAR_TEST_FILTER';
export const FILTERED_TEST_BY_TAGS_FETCH_SUCCEED = 'FILTERED_TEST_BY_TAGS_FETCH_SUCCEED';
export const APPLY_TESTS_FILTERS = 'APPLY_TESTS_FILTERS';
